import { BRAND_IMAGES } from "@/lib/brandImages";

export type CatalogProduct = {
  id: string;
  name: string;
  description: string | null;
  price_ngn: number;
  category: string;
  image_url: string | null;
  stock_quantity: number;
  suitable_for_conditions: string[] | null;
  ingredients: string[] | null;
  product_type: string | null;
  suitable_hair_types: string[] | null;
  suitable_hair_concerns: string[] | null;
};

export const fallbackCatalog: CatalogProduct[] = [
  {
    id: "fallback-skn-001",
    name: "African Black Soap Cleanser",
    description:
      "Traditional Nigerian black soap enriched with shea butter for gentle cleansing. Perfect for oily and acne-prone skin.",
    price_ngn: 3500,
    category: "Cleansers",
    image_url: BRAND_IMAGES.beautyTexture,
    stock_quantity: 100,
    suitable_for_conditions: ["acne", "oily skin", "hyperpigmentation"],
    ingredients: ["African Black Soap", "Shea Butter", "Coconut Oil", "Palm Kernel Oil"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-skn-002",
    name: "Turmeric Brightening Serum",
    description:
      "Potent turmeric and vitamin C serum for hyperpigmentation and dark spots. Nigerian-formulated.",
    price_ngn: 8500,
    category: "Serums",
    image_url: BRAND_IMAGES.skinPortrait,
    stock_quantity: 75,
    suitable_for_conditions: ["hyperpigmentation", "dark spots", "uneven skin tone"],
    ingredients: ["Turmeric Extract", "Vitamin C", "Niacinamide", "Hyaluronic Acid"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-skn-003",
    name: "Shea Butter Moisturizer",
    description: "Rich moisturizer with pure Nigerian shea butter for dry and combination skin.",
    price_ngn: 4500,
    category: "Moisturizers",
    image_url: BRAND_IMAGES.beautyTexture,
    stock_quantity: 120,
    suitable_for_conditions: ["dry skin", "eczema", "sensitive skin"],
    ingredients: ["Shea Butter", "Cocoa Butter", "Vitamin E", "Aloe Vera"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-skn-004",
    name: "Aloe Vera Soothing Gel",
    description: "Pure aloe vera gel for calming irritated and sunburned skin.",
    price_ngn: 2500,
    category: "Treatments",
    image_url: BRAND_IMAGES.skinPortrait,
    stock_quantity: 150,
    suitable_for_conditions: ["sunburn", "irritation", "sensitive skin"],
    ingredients: ["Aloe Vera Gel", "Cucumber Extract", "Green Tea"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-skn-005",
    name: "Kojic Acid Dark Spot Corrector",
    description: "Targeted treatment for stubborn dark spots and acne scars.",
    price_ngn: 7500,
    category: "Treatments",
    image_url: BRAND_IMAGES.beautyTexture,
    stock_quantity: 60,
    suitable_for_conditions: ["dark spots", "acne scars", "hyperpigmentation"],
    ingredients: ["Kojic Acid", "Alpha Arbutin", "Licorice Extract", "Vitamin C"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-skn-006",
    name: "Neem & Tea Tree Acne Treatment",
    description: "Powerful anti-acne formula with neem and tea tree oil.",
    price_ngn: 5500,
    category: "Treatments",
    image_url: BRAND_IMAGES.skinPortrait,
    stock_quantity: 80,
    suitable_for_conditions: ["acne", "oily skin", "blackheads"],
    ingredients: ["Neem Extract", "Tea Tree Oil", "Salicylic Acid", "Zinc"],
    product_type: "skin",
    suitable_hair_types: null,
    suitable_hair_concerns: null,
  },
  {
    id: "fallback-hair-001",
    name: "Deep Moisture Leave-In Conditioner",
    description: "Intensive moisture treatment for 4A-4C hair types. Perfect for dry, coily hair.",
    price_ngn: 5500,
    category: "Conditioners",
    image_url: "/IMG_20250828_155322_1765737829710.jpg",
    stock_quantity: 90,
    suitable_for_conditions: ["dry hair", "breakage"],
    ingredients: ["Shea Butter", "Coconut Oil", "Argan Oil", "Glycerin", "Aloe Vera"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "natural"],
    suitable_hair_concerns: ["dryness", "breakage", "frizz"],
  },
  {
    id: "fallback-hair-002",
    name: "Jamaican Black Castor Oil",
    description: "Traditional JBCO for hair growth, edges, and scalp health.",
    price_ngn: 6500,
    category: "Oils",
    image_url: "/IMG_20250828_154251_1765737829710.jpg",
    stock_quantity: 100,
    suitable_for_conditions: ["hair loss", "thin edges", "slow growth"],
    ingredients: ["Jamaican Black Castor Oil", "Peppermint Oil", "Rosemary Extract"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "relaxed", "transitioning", "natural"],
    suitable_hair_concerns: ["thinning", "slow growth", "weak edges"],
  },
  {
    id: "fallback-hair-003",
    name: "Clarifying Shampoo",
    description: "Sulfate-free clarifying shampoo to remove product buildup without stripping moisture.",
    price_ngn: 4000,
    category: "Shampoos",
    image_url: "/IMG_20250828_154808_1765737829710.jpg",
    stock_quantity: 85,
    suitable_for_conditions: ["product buildup", "oily scalp"],
    ingredients: ["Apple Cider Vinegar", "Charcoal", "Tea Tree Oil", "Peppermint"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "relaxed", "natural"],
    suitable_hair_concerns: ["buildup", "oily scalp", "dandruff"],
  },
  {
    id: "fallback-hair-004",
    name: "Protein Treatment Mask",
    description: "Strengthening protein mask for damaged and over-processed hair.",
    price_ngn: 7000,
    category: "Treatments",
    image_url: "/IMG_20250828_154251_1765737829710.jpg",
    stock_quantity: 70,
    suitable_for_conditions: ["damaged hair", "breakage", "chemical damage"],
    ingredients: ["Hydrolyzed Keratin", "Silk Amino Acids", "Biotin", "Egg Protein"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "relaxed", "transitioning"],
    suitable_hair_concerns: ["breakage", "damage", "weak hair"],
  },
  {
    id: "fallback-hair-005",
    name: "Edge Control Gel",
    description: "Non-flaking edge control for sleek styles without buildup.",
    price_ngn: 2500,
    category: "Styling",
    image_url: "/IMG_20250828_154251_1765737829710.jpg",
    stock_quantity: 120,
    suitable_for_conditions: ["flyaways", "edge styling"],
    ingredients: ["Castor Oil", "Flaxseed Gel", "Argan Oil", "Biotin"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "relaxed", "natural"],
    suitable_hair_concerns: ["edges", "styling"],
  },
  {
    id: "fallback-hair-006",
    name: "Scalp Treatment Oil",
    description: "Anti-dandruff and scalp-soothing treatment oil with neem and tea tree.",
    price_ngn: 5000,
    category: "Treatments",
    image_url: "/IMG_20250828_155449_1765737829710.jpg",
    stock_quantity: 65,
    suitable_for_conditions: ["dandruff", "dry scalp", "itchy scalp"],
    ingredients: ["Neem Oil", "Tea Tree Oil", "Jojoba Oil", "Peppermint", "Rosemary"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "relaxed", "natural", "locs"],
    suitable_hair_concerns: ["dandruff", "itchy scalp", "dry scalp"],
  },
  {
    id: "fallback-hair-007",
    name: "Curl Defining Cream",
    description: "Lightweight cream for defined, bouncy curls and coils.",
    price_ngn: 4500,
    category: "Styling",
    image_url: "/IMG_20250828_154251_1765737829710.jpg",
    stock_quantity: 95,
    suitable_for_conditions: ["undefined curls", "frizz"],
    ingredients: ["Shea Butter", "Flaxseed Gel", "Coconut Oil", "Marshmallow Root"],
    product_type: "hair",
    suitable_hair_types: ["4A", "4B", "4C", "natural"],
    suitable_hair_concerns: ["frizz", "curl definition"],
  },
  {
    id: "fallback-hair-008",
    name: "Transitioning Hair Treatment",
    description: "Special treatment for hair transitioning from relaxed to natural.",
    price_ngn: 6000,
    category: "Treatments",
    image_url: "/IMG_20250828_154251_1765737829710.jpg",
    stock_quantity: 50,
    suitable_for_conditions: ["transitioning hair", "line of demarcation"],
    ingredients: ["Olaplex-like Bond Repair", "Keratin", "Argan Oil", "Avocado Oil"],
    product_type: "hair",
    suitable_hair_types: ["transitioning"],
    suitable_hair_concerns: ["breakage", "weak hair", "transitioning"],
  },
];
