-- Tables needed by the Supabase-hosted API replacement for the old Express backend

ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS payment_method text,
ADD COLUMN IF NOT EXISTS notes text;

CREATE TABLE IF NOT EXISTS public.salon_appointments (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  user_id uuid references auth.users(id) on delete set null,
  service_type text not null,
  service_name text not null,
  appointment_date date not null,
  time_slot text not null,
  duration_minutes integer not null default 30,
  price_ngn numeric(12,2) not null,
  notes text,
  is_registered_user boolean default false,
  status text not null default 'confirmed',
  payment_status text not null default 'unpaid',
  payment_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.payment_transactions (
  id uuid not null default gen_random_uuid() primary key,
  transaction_ref text not null unique,
  payment_type text not null default 'general',
  amount numeric(12,2) not null,
  customer_email text not null,
  customer_name text not null,
  customer_phone text not null,
  booking_id bigint references public.salon_appointments(id) on delete set null,
  plan_id uuid references public.subscription_plans(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending',
  payment_ref text,
  response_code text,
  verified_response jsonb,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.salon_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own salon appointments" ON public.salon_appointments;
CREATE POLICY "Users can view own salon appointments"
ON public.salon_appointments
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create own salon appointments" ON public.salon_appointments;
CREATE POLICY "Users can create own salon appointments"
ON public.salon_appointments
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own salon appointments" ON public.salon_appointments;
CREATE POLICY "Users can update own salon appointments"
ON public.salon_appointments
FOR UPDATE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own payment transactions" ON public.payment_transactions;
CREATE POLICY "Users can view own payment transactions"
ON public.payment_transactions
FOR SELECT
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_salon_appointments_date ON public.salon_appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_salon_appointments_user_id ON public.salon_appointments(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_ref ON public.payment_transactions(transaction_ref);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_id ON public.payment_transactions(user_id);

DROP TRIGGER IF EXISTS update_salon_appointments_updated_at ON public.salon_appointments;
CREATE TRIGGER update_salon_appointments_updated_at
BEFORE UPDATE ON public.salon_appointments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_payment_transactions_updated_at ON public.payment_transactions;
CREATE TRIGGER update_payment_transactions_updated_at
BEFORE UPDATE ON public.payment_transactions
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

UPDATE storage.buckets
SET public = true
WHERE id IN ('skin-scans', 'hair-scans');
